### ISSUE TITLE
Sickness and Absence Policy refers to Harvest

### ISSUE THREAD

**Issue by roberth-k** [infinityworks/policies#108]
https://github.com/infinityworks/policies/blob/master/ISO-9001/SicknessandAbsencePolicy/readme.md#reporting-when-you-are-sick

Should this now reference Kimble instead?

**Comment by Rucknar** [comment]
It should indeed, thanks for spotting. We will get this updated ASAP.

**Comment by roberth-k** [comment]
https://github.com/infinityworks/policies/pull/110
